block_labels = ["needs-decision"]
delete_merged_branches = true
required_approvals = 1
status = [
  "continuous-integration/travis-ci/push",
  "continuous-integration/appveyor/branch"
]
timeout_sec = 14400